language: go

go:
  - "1.13"

arch:
  - amd64
  - ppc64le
  - arm64

os: linux

env:
  - IMAGE_NAME=mellanox/rdma-cni

before_script:
  - go get -u github.com/mattn/goveralls

script:
  - make lint
  - make test-coverage
  - goveralls -coverprofile=rdma-cni.cover -service=travis-ci
 # - make image

#before_deploy:
#  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: echo $TRAVIS_CPU_ARCH
    on:
      branch: multi-arch 
  # Push image to Dockerhub on tag
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $IMAGE_NAME $TRAVIS_TAG $TRAVIS_CPU_ARCH
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^v[0-9].*$"

after_deploy:
   - script: echo "Moshe!! after_success" 
